### ISSUE TITLE
target attribute does not exist in `grpcClient` document

### ISSUE THREAD

**Issue by Kenzku** [OpenLiberty/guide-grpc-intro#58]
In this document: https://openliberty.io/guides/grpc-intro.html#implementing-the-unary-call

```text
Configure the grpcClient feature with the headersToPropagate and target attributes. 
```

there is no `target` attribute in the `grpcClient` document: https://openliberty.io/docs/latest/reference/config/grpcClient.html

do you refer to `host`?

<img width="1444" alt="Screenshot 2023-08-06 at 13 43 29" src="https://github.com/OpenLiberty/guide-grpc-intro/assets/1387249/fffc24e6-5005-47b7-b5a1-2e205b86ece0">

**Comment by shin19991207** [comment]
Hello @Kenzku

Thank you for pointing out the oversight in our guide. Upon review, you are correct: in the `grpcClient` configuration, it should refer to `host` rather than `target`.

Additionally, I want to address the inclusion of the `grpc` feature in the same section you mentioned. The `query` microservice functions as a gRPC client, and the `grpc` feature, which is designed for server-side operations in Open Liberty, isn't required. To be in line with best practice of maintaining minimal configuration, we're working on revising this aspect in our guide.

You can track the progress at https://github.com/OpenLiberty/guide-grpc-intro/pull/61.

**Comment by Kenzku** [comment]
Hej,

Thanks for the reply.

I have noticed the same things that the residual `grpc` feature in the `query`, but forgot to mention.

**Comment by gkwan-ibm** [comment]
close
- the issue was fixed
